"""
GUT (Godot Unit Testing) framework runner and JUnit XML result parsing module
"""

import os
import re
import tempfile
import xml.etree.ElementTree as ET
from typing import Dict, Any, Optional
from ..finder import find_godot_executable
from .runner import run_godot_cmd, build_godot_cmd


def parse_junit_xml(xml_path: str) -> Dict[str, Any]:
    """Parses JUnit XML report output generated by GUT."""
    if not os.path.exists(xml_path):
        return {"passed": 0, "failed": 0, "errors": 0, "total": 0, "failures": []}

    try:
        tree = ET.parse(xml_path)
        root = tree.getroot()

        failures = []
        passed = 0
        failed = 0
        errors = 0

        for testsuite in root.findall(".//testsuite"):
            for testcase in testsuite.findall("testcase"):
                case_name = testcase.get("name", "unknown")
                classname = testcase.get("classname", "")

                failure_elem = testcase.find("failure")
                error_elem = testcase.find("error")

                if failure_elem is not None:
                    failed += 1
                    failures.append(
                        {
                            "test_name": f"{classname}.{case_name}",
                            "message": failure_elem.get("message")
                            or failure_elem.text
                            or "Assertion failed",
                            "severity": "failure",
                        }
                    )
                elif error_elem is not None:
                    errors += 1
                    failures.append(
                        {
                            "test_name": f"{classname}.{case_name}",
                            "message": error_elem.get("message")
                            or error_elem.text
                            or "Error occurred",
                            "severity": "error",
                        }
                    )
                else:
                    passed += 1

        total = passed + failed + errors
        return {
            "passed": passed,
            "failed": failed,
            "errors": errors,
            "total": total,
            "failures": failures,
        }
    except Exception:
        return {"passed": 0, "failed": 0, "errors": 0, "total": 0, "failures": []}


def parse_gut_stdout(stdout: str) -> Dict[str, Any]:
    """Fallback parser for GUT stdout metrics when JUnit XML is not available."""
    passed = 0
    failed = 0
    pending = 0

    pass_match = re.search(r"Passed:\s*(\d+)", stdout)
    if pass_match:
        passed = int(pass_match.group(1))

    fail_match = re.search(r"Failed:\s*(\d+)", stdout)
    if fail_match:
        failed = int(fail_match.group(1))

    pend_match = re.search(r"Pending:\s*(\d+)", stdout)
    if pend_match:
        pending = int(pend_match.group(1))

    return {
        "passed": passed,
        "failed": failed,
        "pending": pending,
        "total": passed + failed + pending,
        "failures": [],
    }


def run_gut_tests(
    project_path: str,
    test_dir: Optional[str] = None,
    select_script: Optional[str] = None,
    timeout: int = 60,
) -> Dict[str, Any]:
    """
    Executes GUT (Godot Unit Testing) suites in headless mode.
    Autodetects `.gutconfig.json` or `addons/gut/gut_cmdln.gd`.
    """
    godot_bin = find_godot_executable()
    abs_project = os.path.abspath(project_path)
    gut_cmdln = os.path.join(abs_project, "addons", "gut", "gut_cmdln.gd")

    if not os.path.exists(gut_cmdln):
        return {
            "status": "error",
            "message": f"GUT runner script not found at {gut_cmdln}. Please ensure GUT plugin is installed in addons/gut/",
        }

    # Generate temporary JUnit XML file for reliable result parsing
    with tempfile.NamedTemporaryFile(suffix=".xml", delete=False) as tf:
        xml_tmp_path = tf.name

    extra_flags = [
        "-d",
        "-s",
        os.path.relpath(gut_cmdln, abs_project),
        "-gexit",
        f"-gjunit_xml_file={xml_tmp_path}",
    ]

    if select_script:
        extra_flags.append(f"-gtest={select_script}")
    elif test_dir:
        extra_flags.append(f"-gdir={test_dir}")

    cmd = build_godot_cmd(
        godot_bin, project_path=abs_project, headless=True, extra_flags=extra_flags
    )

    try:
        res = run_godot_cmd(cmd, timeout=timeout)

        # Parse metrics from JUnit XML or stdout fallback
        metrics = parse_junit_xml(xml_tmp_path)
        if metrics["total"] == 0:
            metrics = parse_gut_stdout(res.stdout)

        has_failures = (
            metrics["failed"] > 0 or metrics["errors"] > 0 or res.returncode != 0
        )
        status = "tests_failed" if has_failures else "success"

        return {
            "status": status,
            "summary": metrics,
            "return_code": res.returncode,
            "stdout": res.stdout,
        }
    except Exception as e:
        return {"status": "error", "message": str(e)}
    finally:
        if os.path.exists(xml_tmp_path):
            os.remove(xml_tmp_path)
